<?php

namespace app\models;

use yii\base\Model;

class SingupForm extends Model
{

    public $last_name;
    public $name;
    public $second_name;
    public $email;
    public $phone;
    public $passhash;

    public function rules()
    {
        return [
          [['last_name', 'name', 'second_name', 'email', 'phone', 'passhash'], 'required', 'message' => 'Заполните поле'],
            [['email'], 'email', 'message' => 'Адрес электронной почты указан не верно']
        ];
    }

    public function attributeLabels()
    {
        return [
            'last_name' => 'Отчество',
            'name' => 'Имя',
            'second_name' => 'Фамилия',
            'email' => 'E-mail',
            'phone' => 'Номер телефона',
            'passhash' => 'Пароль',
        ]; // TODO: Change the autogenerated stub
    }

}