<?php

namespace app\models;

use yii\db\ActiveRecord;

class Status extends ActiveRecord
{
    public function rules()
    {
        return [

        ];
    }

    public function attributeLabels()
    {
        return [

        ]; // TODO: Change the autogenerated stub
    }
}